### PR TITLE
Tournament

### LINKED ISSUE #5: Add Impersonation
- [ ] Upgrade to latest stable version of node
 - [ ] Add the ability to impersonate requests using `API_SECRET:username` as a authToken.

### PR DESCRIPTION
**Pull request by elmigranto**
Closes #5.

I failed to run this under docker, not sure what the reason is:

```
$ docker-compose up              
ganomedecoordinator_couchGames_1 is up-to-date
ganomedecoordinator_redisAuth_1 is up-to-date
Creating ganomedecoordinator_app_1

ERROR: for app  Cannot create container for service app: readdirent: not a directory
ERROR: Encountered errors while bringing up the project.
```

Tried changing some stuff related directories/paths inside docker's files, didn't help. Any suggestions?

### CODE REVIEW

**Comment by j3k0** [comment]
Concerning Docker. Maybe some special chars or spaces in the PATH to your working directory? I think docker for mac solved a few bugs on OSX related to paths recently, worth updating if you didn't already. You can try forcing a `docker-compose build` too.

This PR seems still experimental (github repo and beta versions references from package.json). I'll merge and deploy to prod when stabilized.

**Comment by elmigranto** [comment]
Updated deps, no luck with Docker, though. Seems up to date, path is alpha-numerical with `-`, works fine for other repos. So I ultimately left that part as it is. Does it run for you?

Tried `docker-compose build --force-rm --no-cache`, same cryptic error message… Here're my versions and path, seems up to date:

``` sh
# elmigranto @ elmacbook in ~/Work/j3k0/ganomede-coordinator on git:tournament o [16:59:42] 
$ docker -v && docker-machine -v && docker-compose -v
Docker version 1.12.1, build 23cf638
docker-machine version 0.8.2, build e18a919
docker-compose version 1.8.0, build unknown
```

**Comment by j3k0** [comment]
It's now required to add `./` before relative path in docker-compose volumes, since docker introduced named volumes that could create confusion.

**Comment by elmigranto** [comment]
I see. Relative paths used to be folders-only… Okay then.

**Pull request merged**
